services:
  mongo:
    image: mongo:6
    container_name: apexblog-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: apexblog-server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/apexblogdb
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: apexblog-client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

volumes:
  mongo-data:
