services:
  mongo:
    image: mongo:6
    container_name: apexblog-mongo
    restart: always
    ports: ["27017:27017"]
    volumes: [mongo-data:/data/db]

  server:
    build: ./server            
    container_name: apexblog-server
    ports: ["4000:4000"]
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file: ./server/.env.production 
    environment:
      - NODE_ENV=production
    depends_on: [mongo]

  client:
    build:
      context: ./client                 
      args:                             # <-- pass API url to React build
        REACT_APP_API_URL: https://gurusys-blog-api.onrender.com
    container_name: apexblog-client
    ports: ["3000:80"]
    environment:
      - NODE_ENV=production
    env_file: ./client/.env.production

volumes:
  mongo-data:
